
# Project information
site_name: Luis Robaina - Professional Website
site_url: https://luisrobaina.github.io/
site_author: Luis Robaina

theme:
  name: dracula
  language: en
  logo: images/yo2.png
  favicon: images/logo_fam.png


plugins:
  - search

nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md